# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setStyleSheet("background-color:rgb(255, 185, 185);")
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(30)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.service_choice_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.service_choice_radioButton.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.service_choice_radioButton.setFont(font)
        self.service_choice_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.service_choice_radioButton.setChecked(True)
        self.service_choice_radioButton.setObjectName("service_choice_radioButton")
        self.horizontalLayout_5.addWidget(self.service_choice_radioButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apikey_label = QtWidgets.QLabel(self.groupBox)
        self.apikey_label.setObjectName("apikey_label")
        self.horizontalLayout.addWidget(self.apikey_label)
        self.apikey_edit = QtWidgets.QLineEdit(self.groupBox)
        self.apikey_edit.setObjectName("apikey_edit")
        self.horizontalLayout.addWidget(self.apikey_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.secretkey_label = QtWidgets.QLabel(self.groupBox)
        self.secretkey_label.setObjectName("secretkey_label")
        self.horizontalLayout_2.addWidget(self.secretkey_label)
        self.secretkey_edit = QtWidgets.QLineEdit(self.groupBox)
        self.secretkey_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.secretkey_edit.setInputMask("")
        self.secretkey_edit.setText("")
        self.secretkey_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.secretkey_edit.setObjectName("secretkey_edit")
        self.horizontalLayout_2.addWidget(self.secretkey_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.connection_button = QtWidgets.QPushButton(self.groupBox)
        self.connection_button.setMinimumSize(QtCore.QSize(0, 40))
        self.connection_button.setObjectName("connection_button")
        self.horizontalLayout_4.addWidget(self.connection_button)
        self.connection_status_label = QtWidgets.QLabel(self.groupBox)
        self.connection_status_label.setObjectName("connection_status_label")
        self.horizontalLayout_4.addWidget(self.connection_status_label)
        self.voice_language_combobox = QtWidgets.QComboBox(self.groupBox)
        self.voice_language_combobox.setMinimumSize(QtCore.QSize(0, 25))
        self.voice_language_combobox.setObjectName("voice_language_combobox")
        self.voice_language_combobox.addItem("")
        self.voice_language_combobox.addItem("")
        self.voice_language_combobox.addItem("")
        self.voice_language_combobox.addItem("")
        self.voice_language_combobox.addItem("")
        self.horizontalLayout_4.addWidget(self.voice_language_combobox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.file_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.file_tableWidget.setPalette(palette)
        self.file_tableWidget.setObjectName("file_tableWidget")
        self.file_tableWidget.setColumnCount(3)
        self.file_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.file_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.file_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.file_tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.file_tableWidget, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.open_input_dir_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_input_dir_pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.open_input_dir_pushButton.setObjectName("open_input_dir_pushButton")
        self.horizontalLayout_3.addWidget(self.open_input_dir_pushButton)
        self.choose_save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.choose_save_pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.choose_save_pushButton.setObjectName("choose_save_pushButton")
        self.horizontalLayout_3.addWidget(self.choose_save_pushButton)
        self.begin_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.begin_pushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.begin_pushButton.setObjectName("begin_pushButton")
        self.horizontalLayout_3.addWidget(self.begin_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_key = QtWidgets.QAction(MainWindow)
        self.action_key.setObjectName("action_key")
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.service_choice_radioButton.setToolTip(_translate("MainWindow", "目前只支持百度智能云，看需求添加腾讯云、阿里云、华为云等等"))
        self.service_choice_radioButton.setStatusTip(_translate("MainWindow", "目前只支持百度智能云，看需求添加腾讯云、阿里云、华为云等等"))
        self.service_choice_radioButton.setText(_translate("MainWindow", "百度智能云"))
        self.apikey_label.setToolTip(_translate("MainWindow", "请填入在百度智能云里申请的应用API Key"))
        self.apikey_label.setStatusTip(_translate("MainWindow", "请填入在百度智能云里申请的应用API Key"))
        self.apikey_label.setText(_translate("MainWindow", "API Key:    "))
        self.apikey_edit.setToolTip(_translate("MainWindow", "请填入在百度智能云里申请的应用API Key"))
        self.apikey_edit.setStatusTip(_translate("MainWindow", "请填入在百度智能云里申请的应用API Key"))
        self.apikey_edit.setPlaceholderText(_translate("MainWindow", "请填入在百度智能云里申请的应用API Key"))
        self.secretkey_label.setToolTip(_translate("MainWindow", "请填入在百度智能云里申请的应用Secret Key"))
        self.secretkey_label.setStatusTip(_translate("MainWindow", "请填入在百度智能云里申请的应用Secret Key"))
        self.secretkey_label.setText(_translate("MainWindow", "Secret Key: "))
        self.secretkey_edit.setToolTip(_translate("MainWindow", "请填入在百度智能云里申请的应用Secret Key"))
        self.secretkey_edit.setStatusTip(_translate("MainWindow", "请填入在百度智能云里申请的应用Secret Key"))
        self.secretkey_edit.setPlaceholderText(_translate("MainWindow", "请填入在百度智能云里申请的应用Secret Key"))
        self.connection_button.setText(_translate("MainWindow", "连接"))
        self.connection_status_label.setText(_translate("MainWindow", "连接成功"))
        self.voice_language_combobox.setItemText(0, _translate("MainWindow", "普通话"))
        self.voice_language_combobox.setItemText(1, _translate("MainWindow", "英语"))
        self.voice_language_combobox.setItemText(2, _translate("MainWindow", "粤语"))
        self.voice_language_combobox.setItemText(3, _translate("MainWindow", "四川话"))
        self.voice_language_combobox.setItemText(4, _translate("MainWindow", "普通话远场"))
        item = self.file_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.file_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "修改日期"))
        item = self.file_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "大小"))
        self.open_input_dir_pushButton.setText(_translate("MainWindow", "打开输入文件夹"))
        self.choose_save_pushButton.setText(_translate("MainWindow", "选择保存位置"))
        self.begin_pushButton.setText(_translate("MainWindow", "转换"))
        self.menu_2.setTitle(_translate("MainWindow", "使用说明"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.menu.setTitle(_translate("MainWindow", "捐助"))
        self.menu_4.setTitle(_translate("MainWindow", "反馈"))
        self.menu_5.setTitle(_translate("MainWindow", "官网"))
        self.action_key.setText(_translate("MainWindow", "添加百度云key"))
